/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.ruter.events.avro.tps;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Quay for a Stop Place */
@org.apache.avro.specific.AvroGenerated
public class Quay extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5260090876431802778L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Quay\",\"namespace\":\"no.ruter.events.avro.tps\",\"doc\":\"Quay for a Stop Place\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"position\",\"type\":{\"type\":\"record\",\"name\":\"Position\",\"doc\":\"Position\",\"fields\":[{\"name\":\"lat\",\"type\":\"double\"},{\"name\":\"lon\",\"type\":\"double\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Quay> ENCODER =
      new BinaryMessageEncoder<Quay>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Quay> DECODER =
      new BinaryMessageDecoder<Quay>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Quay> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Quay> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Quay>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Quay to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Quay from a ByteBuffer. */
  public static Quay fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public no.ruter.events.avro.tps.Position position;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Quay() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param position The new value for position
   */
  public Quay(java.lang.CharSequence id, no.ruter.events.avro.tps.Position position) {
    this.id = id;
    this.position = position;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return position;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: position = (no.ruter.events.avro.tps.Position)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'position' field.
   * @return The value of the 'position' field.
   */
  public no.ruter.events.avro.tps.Position getPosition() {
    return position;
  }

  /**
   * Sets the value of the 'position' field.
   * @param value the value to set.
   */
  public void setPosition(no.ruter.events.avro.tps.Position value) {
    this.position = value;
  }

  /**
   * Creates a new Quay RecordBuilder.
   * @return A new Quay RecordBuilder
   */
  public static no.ruter.events.avro.tps.Quay.Builder newBuilder() {
    return new no.ruter.events.avro.tps.Quay.Builder();
  }

  /**
   * Creates a new Quay RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Quay RecordBuilder
   */
  public static no.ruter.events.avro.tps.Quay.Builder newBuilder(no.ruter.events.avro.tps.Quay.Builder other) {
    return new no.ruter.events.avro.tps.Quay.Builder(other);
  }

  /**
   * Creates a new Quay RecordBuilder by copying an existing Quay instance.
   * @param other The existing instance to copy.
   * @return A new Quay RecordBuilder
   */
  public static no.ruter.events.avro.tps.Quay.Builder newBuilder(no.ruter.events.avro.tps.Quay other) {
    return new no.ruter.events.avro.tps.Quay.Builder(other);
  }

  /**
   * RecordBuilder for Quay instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Quay>
    implements org.apache.avro.data.RecordBuilder<Quay> {

    private java.lang.CharSequence id;
    private no.ruter.events.avro.tps.Position position;
    private no.ruter.events.avro.tps.Position.Builder positionBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.ruter.events.avro.tps.Quay.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.position)) {
        this.position = data().deepCopy(fields()[1].schema(), other.position);
        fieldSetFlags()[1] = true;
      }
      if (other.hasPositionBuilder()) {
        this.positionBuilder = no.ruter.events.avro.tps.Position.newBuilder(other.getPositionBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Quay instance
     * @param other The existing instance to copy.
     */
    private Builder(no.ruter.events.avro.tps.Quay other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.position)) {
        this.position = data().deepCopy(fields()[1].schema(), other.position);
        fieldSetFlags()[1] = true;
      }
      this.positionBuilder = null;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public no.ruter.events.avro.tps.Quay.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public no.ruter.events.avro.tps.Quay.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'position' field.
      * @return The value.
      */
    public no.ruter.events.avro.tps.Position getPosition() {
      return position;
    }

    /**
      * Sets the value of the 'position' field.
      * @param value The value of 'position'.
      * @return This builder.
      */
    public no.ruter.events.avro.tps.Quay.Builder setPosition(no.ruter.events.avro.tps.Position value) {
      validate(fields()[1], value);
      this.positionBuilder = null;
      this.position = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'position' field has been set.
      * @return True if the 'position' field has been set, false otherwise.
      */
    public boolean hasPosition() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'position' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public no.ruter.events.avro.tps.Position.Builder getPositionBuilder() {
      if (positionBuilder == null) {
        if (hasPosition()) {
          setPositionBuilder(no.ruter.events.avro.tps.Position.newBuilder(position));
        } else {
          setPositionBuilder(no.ruter.events.avro.tps.Position.newBuilder());
        }
      }
      return positionBuilder;
    }

    /**
     * Sets the Builder instance for the 'position' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public no.ruter.events.avro.tps.Quay.Builder setPositionBuilder(no.ruter.events.avro.tps.Position.Builder value) {
      clearPosition();
      positionBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'position' field has an active Builder instance
     * @return True if the 'position' field has an active Builder instance
     */
    public boolean hasPositionBuilder() {
      return positionBuilder != null;
    }

    /**
      * Clears the value of the 'position' field.
      * @return This builder.
      */
    public no.ruter.events.avro.tps.Quay.Builder clearPosition() {
      position = null;
      positionBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Quay build() {
      try {
        Quay record = new Quay();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (positionBuilder != null) {
          record.position = this.positionBuilder.build();
        } else {
          record.position = fieldSetFlags()[1] ? this.position : (no.ruter.events.avro.tps.Position) defaultValue(fields()[1]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Quay>
    WRITER$ = (org.apache.avro.io.DatumWriter<Quay>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Quay>
    READER$ = (org.apache.avro.io.DatumReader<Quay>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
