/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.ruter.events.avro.tps;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Route */
@org.apache.avro.specific.AvroGenerated
public class Route extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4824631739976861640L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Route\",\"namespace\":\"no.ruter.events.avro.tps\",\"doc\":\"Route\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"line\",\"type\":{\"type\":\"record\",\"name\":\"Line\",\"doc\":\"Line\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"publicCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"colour\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"transportMode\",\"type\":[\"null\",\"string\"],\"default\":null}]}},{\"name\":\"name\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Route> ENCODER =
      new BinaryMessageEncoder<Route>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Route> DECODER =
      new BinaryMessageDecoder<Route>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Route> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Route> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Route>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Route to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Route from a ByteBuffer. */
  public static Route fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public no.ruter.events.avro.tps.Line line;
  @Deprecated public java.lang.CharSequence name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Route() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param line The new value for line
   * @param name The new value for name
   */
  public Route(java.lang.CharSequence id, no.ruter.events.avro.tps.Line line, java.lang.CharSequence name) {
    this.id = id;
    this.line = line;
    this.name = name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return line;
    case 2: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: line = (no.ruter.events.avro.tps.Line)value$; break;
    case 2: name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'line' field.
   * @return The value of the 'line' field.
   */
  public no.ruter.events.avro.tps.Line getLine() {
    return line;
  }

  /**
   * Sets the value of the 'line' field.
   * @param value the value to set.
   */
  public void setLine(no.ruter.events.avro.tps.Line value) {
    this.line = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Creates a new Route RecordBuilder.
   * @return A new Route RecordBuilder
   */
  public static no.ruter.events.avro.tps.Route.Builder newBuilder() {
    return new no.ruter.events.avro.tps.Route.Builder();
  }

  /**
   * Creates a new Route RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Route RecordBuilder
   */
  public static no.ruter.events.avro.tps.Route.Builder newBuilder(no.ruter.events.avro.tps.Route.Builder other) {
    return new no.ruter.events.avro.tps.Route.Builder(other);
  }

  /**
   * Creates a new Route RecordBuilder by copying an existing Route instance.
   * @param other The existing instance to copy.
   * @return A new Route RecordBuilder
   */
  public static no.ruter.events.avro.tps.Route.Builder newBuilder(no.ruter.events.avro.tps.Route other) {
    return new no.ruter.events.avro.tps.Route.Builder(other);
  }

  /**
   * RecordBuilder for Route instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Route>
    implements org.apache.avro.data.RecordBuilder<Route> {

    private java.lang.CharSequence id;
    private no.ruter.events.avro.tps.Line line;
    private no.ruter.events.avro.tps.Line.Builder lineBuilder;
    private java.lang.CharSequence name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.ruter.events.avro.tps.Route.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.line)) {
        this.line = data().deepCopy(fields()[1].schema(), other.line);
        fieldSetFlags()[1] = true;
      }
      if (other.hasLineBuilder()) {
        this.lineBuilder = no.ruter.events.avro.tps.Line.newBuilder(other.getLineBuilder());
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Route instance
     * @param other The existing instance to copy.
     */
    private Builder(no.ruter.events.avro.tps.Route other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.line)) {
        this.line = data().deepCopy(fields()[1].schema(), other.line);
        fieldSetFlags()[1] = true;
      }
      this.lineBuilder = null;
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public no.ruter.events.avro.tps.Route.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public no.ruter.events.avro.tps.Route.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'line' field.
      * @return The value.
      */
    public no.ruter.events.avro.tps.Line getLine() {
      return line;
    }

    /**
      * Sets the value of the 'line' field.
      * @param value The value of 'line'.
      * @return This builder.
      */
    public no.ruter.events.avro.tps.Route.Builder setLine(no.ruter.events.avro.tps.Line value) {
      validate(fields()[1], value);
      this.lineBuilder = null;
      this.line = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'line' field has been set.
      * @return True if the 'line' field has been set, false otherwise.
      */
    public boolean hasLine() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'line' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public no.ruter.events.avro.tps.Line.Builder getLineBuilder() {
      if (lineBuilder == null) {
        if (hasLine()) {
          setLineBuilder(no.ruter.events.avro.tps.Line.newBuilder(line));
        } else {
          setLineBuilder(no.ruter.events.avro.tps.Line.newBuilder());
        }
      }
      return lineBuilder;
    }

    /**
     * Sets the Builder instance for the 'line' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public no.ruter.events.avro.tps.Route.Builder setLineBuilder(no.ruter.events.avro.tps.Line.Builder value) {
      clearLine();
      lineBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'line' field has an active Builder instance
     * @return True if the 'line' field has an active Builder instance
     */
    public boolean hasLineBuilder() {
      return lineBuilder != null;
    }

    /**
      * Clears the value of the 'line' field.
      * @return This builder.
      */
    public no.ruter.events.avro.tps.Route.Builder clearLine() {
      line = null;
      lineBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public no.ruter.events.avro.tps.Route.Builder setName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public no.ruter.events.avro.tps.Route.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Route build() {
      try {
        Route record = new Route();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (lineBuilder != null) {
          record.line = this.lineBuilder.build();
        } else {
          record.line = fieldSetFlags()[1] ? this.line : (no.ruter.events.avro.tps.Line) defaultValue(fields()[1]);
        }
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Route>
    WRITER$ = (org.apache.avro.io.DatumWriter<Route>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Route>
    READER$ = (org.apache.avro.io.DatumReader<Route>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
