/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.ruter.avro.entity.actual.journey.status;
@SuppressWarnings("all")
/** Reason for ending */
@org.apache.avro.specific.AvroGenerated
public enum EndStatus {
  FINISHED, CANCELLED, DETECTED, TIMEOUT, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EndStatus\",\"namespace\":\"no.ruter.avro.entity.actual.journey.status\",\"doc\":\"Reason for ending\",\"symbols\":[\"FINISHED\",\"CANCELLED\",\"DETECTED\",\"TIMEOUT\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
