/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.ruter.avro.entity.actual.journey.status;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EntityPartition extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5860273397734076531L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EntityPartition\",\"namespace\":\"no.ruter.avro.entity.actual.journey.status\",\"fields\":[{\"name\":\"Key\",\"type\":\"string\",\"doc\":\"The key of an entity. All entities must use the key attribute to store their primary key\"},{\"name\":\"Status\",\"type\":{\"type\":\"enum\",\"name\":\"Status\",\"doc\":\"Last known status of the actual Journey.\",\"symbols\":[\"COMMITTED\",\"RUNNING\",\"ENDED\"]},\"doc\":\"Last known status of the actual Journey.\"},{\"name\":\"EndStatus\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"EndStatus\",\"doc\":\"Reason for ending\",\"symbols\":[\"FINISHED\",\"CANCELLED\",\"DETECTED\",\"TIMEOUT\",\"UNKNOWN\"]}],\"doc\":\"Reason for ending\",\"default\":null},{\"name\":\"LastActualCallRef\",\"type\":[\"null\",\"string\"],\"doc\":\"Reference to last actual call on journey.\",\"default\":null},{\"name\":\"NextActualCallRef\",\"type\":[\"null\",\"string\"],\"doc\":\"Reference to next planned actual call on journey.\",\"default\":null},{\"name\":\"JourneyDelay\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"JourneyDelay\",\"doc\":\"Delay object\",\"fields\":[{\"name\":\"Delay\",\"type\":\"int\",\"doc\":\"Delay in seconds. Negative numbers are ahead of shedule.\"},{\"name\":\"Source\",\"type\":{\"type\":\"enum\",\"name\":\"Source\",\"doc\":\"Source of delay information.\",\"symbols\":[\"SIS\",\"UNKNOWN\"]},\"doc\":\"Source of delay information.\"},{\"name\":\"DelayTimestamp\",\"type\":[\"null\",\"string\"],\"doc\":\"Timestamp for delay estimation.\",\"default\":null}]}],\"doc\":\"Delay object\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EntityPartition> ENCODER =
      new BinaryMessageEncoder<EntityPartition>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EntityPartition> DECODER =
      new BinaryMessageDecoder<EntityPartition>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EntityPartition> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EntityPartition> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EntityPartition>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EntityPartition to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EntityPartition from a ByteBuffer. */
  public static EntityPartition fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The key of an entity. All entities must use the key attribute to store their primary key */
  @Deprecated public java.lang.CharSequence Key;
  /** Last known status of the actual Journey. */
  @Deprecated public no.ruter.avro.entity.actual.journey.status.Status Status;
  /** Reason for ending */
  @Deprecated public no.ruter.avro.entity.actual.journey.status.EndStatus EndStatus;
  /** Reference to last actual call on journey. */
  @Deprecated public java.lang.CharSequence LastActualCallRef;
  /** Reference to next planned actual call on journey. */
  @Deprecated public java.lang.CharSequence NextActualCallRef;
  /** Delay object */
  @Deprecated public no.ruter.avro.entity.actual.journey.status.JourneyDelay JourneyDelay;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EntityPartition() {}

  /**
   * All-args constructor.
   * @param Key The key of an entity. All entities must use the key attribute to store their primary key
   * @param Status Last known status of the actual Journey.
   * @param EndStatus Reason for ending
   * @param LastActualCallRef Reference to last actual call on journey.
   * @param NextActualCallRef Reference to next planned actual call on journey.
   * @param JourneyDelay Delay object
   */
  public EntityPartition(java.lang.CharSequence Key, no.ruter.avro.entity.actual.journey.status.Status Status, no.ruter.avro.entity.actual.journey.status.EndStatus EndStatus, java.lang.CharSequence LastActualCallRef, java.lang.CharSequence NextActualCallRef, no.ruter.avro.entity.actual.journey.status.JourneyDelay JourneyDelay) {
    this.Key = Key;
    this.Status = Status;
    this.EndStatus = EndStatus;
    this.LastActualCallRef = LastActualCallRef;
    this.NextActualCallRef = NextActualCallRef;
    this.JourneyDelay = JourneyDelay;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Key;
    case 1: return Status;
    case 2: return EndStatus;
    case 3: return LastActualCallRef;
    case 4: return NextActualCallRef;
    case 5: return JourneyDelay;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Key = (java.lang.CharSequence)value$; break;
    case 1: Status = (no.ruter.avro.entity.actual.journey.status.Status)value$; break;
    case 2: EndStatus = (no.ruter.avro.entity.actual.journey.status.EndStatus)value$; break;
    case 3: LastActualCallRef = (java.lang.CharSequence)value$; break;
    case 4: NextActualCallRef = (java.lang.CharSequence)value$; break;
    case 5: JourneyDelay = (no.ruter.avro.entity.actual.journey.status.JourneyDelay)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Key' field.
   * @return The key of an entity. All entities must use the key attribute to store their primary key
   */
  public java.lang.CharSequence getKey() {
    return Key;
  }

  /**
   * Sets the value of the 'Key' field.
   * The key of an entity. All entities must use the key attribute to store their primary key
   * @param value the value to set.
   */
  public void setKey(java.lang.CharSequence value) {
    this.Key = value;
  }

  /**
   * Gets the value of the 'Status' field.
   * @return Last known status of the actual Journey.
   */
  public no.ruter.avro.entity.actual.journey.status.Status getStatus() {
    return Status;
  }

  /**
   * Sets the value of the 'Status' field.
   * Last known status of the actual Journey.
   * @param value the value to set.
   */
  public void setStatus(no.ruter.avro.entity.actual.journey.status.Status value) {
    this.Status = value;
  }

  /**
   * Gets the value of the 'EndStatus' field.
   * @return Reason for ending
   */
  public no.ruter.avro.entity.actual.journey.status.EndStatus getEndStatus() {
    return EndStatus;
  }

  /**
   * Sets the value of the 'EndStatus' field.
   * Reason for ending
   * @param value the value to set.
   */
  public void setEndStatus(no.ruter.avro.entity.actual.journey.status.EndStatus value) {
    this.EndStatus = value;
  }

  /**
   * Gets the value of the 'LastActualCallRef' field.
   * @return Reference to last actual call on journey.
   */
  public java.lang.CharSequence getLastActualCallRef() {
    return LastActualCallRef;
  }

  /**
   * Sets the value of the 'LastActualCallRef' field.
   * Reference to last actual call on journey.
   * @param value the value to set.
   */
  public void setLastActualCallRef(java.lang.CharSequence value) {
    this.LastActualCallRef = value;
  }

  /**
   * Gets the value of the 'NextActualCallRef' field.
   * @return Reference to next planned actual call on journey.
   */
  public java.lang.CharSequence getNextActualCallRef() {
    return NextActualCallRef;
  }

  /**
   * Sets the value of the 'NextActualCallRef' field.
   * Reference to next planned actual call on journey.
   * @param value the value to set.
   */
  public void setNextActualCallRef(java.lang.CharSequence value) {
    this.NextActualCallRef = value;
  }

  /**
   * Gets the value of the 'JourneyDelay' field.
   * @return Delay object
   */
  public no.ruter.avro.entity.actual.journey.status.JourneyDelay getJourneyDelay() {
    return JourneyDelay;
  }

  /**
   * Sets the value of the 'JourneyDelay' field.
   * Delay object
   * @param value the value to set.
   */
  public void setJourneyDelay(no.ruter.avro.entity.actual.journey.status.JourneyDelay value) {
    this.JourneyDelay = value;
  }

  /**
   * Creates a new EntityPartition RecordBuilder.
   * @return A new EntityPartition RecordBuilder
   */
  public static no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder newBuilder() {
    return new no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder();
  }

  /**
   * Creates a new EntityPartition RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EntityPartition RecordBuilder
   */
  public static no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder newBuilder(no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder other) {
    return new no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder(other);
  }

  /**
   * Creates a new EntityPartition RecordBuilder by copying an existing EntityPartition instance.
   * @param other The existing instance to copy.
   * @return A new EntityPartition RecordBuilder
   */
  public static no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder newBuilder(no.ruter.avro.entity.actual.journey.status.EntityPartition other) {
    return new no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder(other);
  }

  /**
   * RecordBuilder for EntityPartition instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EntityPartition>
    implements org.apache.avro.data.RecordBuilder<EntityPartition> {

    /** The key of an entity. All entities must use the key attribute to store their primary key */
    private java.lang.CharSequence Key;
    /** Last known status of the actual Journey. */
    private no.ruter.avro.entity.actual.journey.status.Status Status;
    /** Reason for ending */
    private no.ruter.avro.entity.actual.journey.status.EndStatus EndStatus;
    /** Reference to last actual call on journey. */
    private java.lang.CharSequence LastActualCallRef;
    /** Reference to next planned actual call on journey. */
    private java.lang.CharSequence NextActualCallRef;
    /** Delay object */
    private no.ruter.avro.entity.actual.journey.status.JourneyDelay JourneyDelay;
    private no.ruter.avro.entity.actual.journey.status.JourneyDelay.Builder JourneyDelayBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Key)) {
        this.Key = data().deepCopy(fields()[0].schema(), other.Key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Status)) {
        this.Status = data().deepCopy(fields()[1].schema(), other.Status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.EndStatus)) {
        this.EndStatus = data().deepCopy(fields()[2].schema(), other.EndStatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.LastActualCallRef)) {
        this.LastActualCallRef = data().deepCopy(fields()[3].schema(), other.LastActualCallRef);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.NextActualCallRef)) {
        this.NextActualCallRef = data().deepCopy(fields()[4].schema(), other.NextActualCallRef);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.JourneyDelay)) {
        this.JourneyDelay = data().deepCopy(fields()[5].schema(), other.JourneyDelay);
        fieldSetFlags()[5] = true;
      }
      if (other.hasJourneyDelayBuilder()) {
        this.JourneyDelayBuilder = no.ruter.avro.entity.actual.journey.status.JourneyDelay.newBuilder(other.getJourneyDelayBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing EntityPartition instance
     * @param other The existing instance to copy.
     */
    private Builder(no.ruter.avro.entity.actual.journey.status.EntityPartition other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Key)) {
        this.Key = data().deepCopy(fields()[0].schema(), other.Key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Status)) {
        this.Status = data().deepCopy(fields()[1].schema(), other.Status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.EndStatus)) {
        this.EndStatus = data().deepCopy(fields()[2].schema(), other.EndStatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.LastActualCallRef)) {
        this.LastActualCallRef = data().deepCopy(fields()[3].schema(), other.LastActualCallRef);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.NextActualCallRef)) {
        this.NextActualCallRef = data().deepCopy(fields()[4].schema(), other.NextActualCallRef);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.JourneyDelay)) {
        this.JourneyDelay = data().deepCopy(fields()[5].schema(), other.JourneyDelay);
        fieldSetFlags()[5] = true;
      }
      this.JourneyDelayBuilder = null;
    }

    /**
      * Gets the value of the 'Key' field.
      * The key of an entity. All entities must use the key attribute to store their primary key
      * @return The value.
      */
    public java.lang.CharSequence getKey() {
      return Key;
    }

    /**
      * Sets the value of the 'Key' field.
      * The key of an entity. All entities must use the key attribute to store their primary key
      * @param value The value of 'Key'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder setKey(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Key' field has been set.
      * The key of an entity. All entities must use the key attribute to store their primary key
      * @return True if the 'Key' field has been set, false otherwise.
      */
    public boolean hasKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Key' field.
      * The key of an entity. All entities must use the key attribute to store their primary key
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder clearKey() {
      Key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Status' field.
      * Last known status of the actual Journey.
      * @return The value.
      */
    public no.ruter.avro.entity.actual.journey.status.Status getStatus() {
      return Status;
    }

    /**
      * Sets the value of the 'Status' field.
      * Last known status of the actual Journey.
      * @param value The value of 'Status'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder setStatus(no.ruter.avro.entity.actual.journey.status.Status value) {
      validate(fields()[1], value);
      this.Status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Status' field has been set.
      * Last known status of the actual Journey.
      * @return True if the 'Status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Status' field.
      * Last known status of the actual Journey.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder clearStatus() {
      Status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'EndStatus' field.
      * Reason for ending
      * @return The value.
      */
    public no.ruter.avro.entity.actual.journey.status.EndStatus getEndStatus() {
      return EndStatus;
    }

    /**
      * Sets the value of the 'EndStatus' field.
      * Reason for ending
      * @param value The value of 'EndStatus'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder setEndStatus(no.ruter.avro.entity.actual.journey.status.EndStatus value) {
      validate(fields()[2], value);
      this.EndStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'EndStatus' field has been set.
      * Reason for ending
      * @return True if the 'EndStatus' field has been set, false otherwise.
      */
    public boolean hasEndStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'EndStatus' field.
      * Reason for ending
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder clearEndStatus() {
      EndStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'LastActualCallRef' field.
      * Reference to last actual call on journey.
      * @return The value.
      */
    public java.lang.CharSequence getLastActualCallRef() {
      return LastActualCallRef;
    }

    /**
      * Sets the value of the 'LastActualCallRef' field.
      * Reference to last actual call on journey.
      * @param value The value of 'LastActualCallRef'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder setLastActualCallRef(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.LastActualCallRef = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'LastActualCallRef' field has been set.
      * Reference to last actual call on journey.
      * @return True if the 'LastActualCallRef' field has been set, false otherwise.
      */
    public boolean hasLastActualCallRef() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'LastActualCallRef' field.
      * Reference to last actual call on journey.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder clearLastActualCallRef() {
      LastActualCallRef = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'NextActualCallRef' field.
      * Reference to next planned actual call on journey.
      * @return The value.
      */
    public java.lang.CharSequence getNextActualCallRef() {
      return NextActualCallRef;
    }

    /**
      * Sets the value of the 'NextActualCallRef' field.
      * Reference to next planned actual call on journey.
      * @param value The value of 'NextActualCallRef'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder setNextActualCallRef(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.NextActualCallRef = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'NextActualCallRef' field has been set.
      * Reference to next planned actual call on journey.
      * @return True if the 'NextActualCallRef' field has been set, false otherwise.
      */
    public boolean hasNextActualCallRef() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'NextActualCallRef' field.
      * Reference to next planned actual call on journey.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder clearNextActualCallRef() {
      NextActualCallRef = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'JourneyDelay' field.
      * Delay object
      * @return The value.
      */
    public no.ruter.avro.entity.actual.journey.status.JourneyDelay getJourneyDelay() {
      return JourneyDelay;
    }

    /**
      * Sets the value of the 'JourneyDelay' field.
      * Delay object
      * @param value The value of 'JourneyDelay'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder setJourneyDelay(no.ruter.avro.entity.actual.journey.status.JourneyDelay value) {
      validate(fields()[5], value);
      this.JourneyDelayBuilder = null;
      this.JourneyDelay = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'JourneyDelay' field has been set.
      * Delay object
      * @return True if the 'JourneyDelay' field has been set, false otherwise.
      */
    public boolean hasJourneyDelay() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'JourneyDelay' field and creates one if it doesn't exist yet.
     * Delay object
     * @return This builder.
     */
    public no.ruter.avro.entity.actual.journey.status.JourneyDelay.Builder getJourneyDelayBuilder() {
      if (JourneyDelayBuilder == null) {
        if (hasJourneyDelay()) {
          setJourneyDelayBuilder(no.ruter.avro.entity.actual.journey.status.JourneyDelay.newBuilder(JourneyDelay));
        } else {
          setJourneyDelayBuilder(no.ruter.avro.entity.actual.journey.status.JourneyDelay.newBuilder());
        }
      }
      return JourneyDelayBuilder;
    }

    /**
     * Sets the Builder instance for the 'JourneyDelay' field
     * Delay object
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder setJourneyDelayBuilder(no.ruter.avro.entity.actual.journey.status.JourneyDelay.Builder value) {
      clearJourneyDelay();
      JourneyDelayBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'JourneyDelay' field has an active Builder instance
     * Delay object
     * @return True if the 'JourneyDelay' field has an active Builder instance
     */
    public boolean hasJourneyDelayBuilder() {
      return JourneyDelayBuilder != null;
    }

    /**
      * Clears the value of the 'JourneyDelay' field.
      * Delay object
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.journey.status.EntityPartition.Builder clearJourneyDelay() {
      JourneyDelay = null;
      JourneyDelayBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EntityPartition build() {
      try {
        EntityPartition record = new EntityPartition();
        record.Key = fieldSetFlags()[0] ? this.Key : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Status = fieldSetFlags()[1] ? this.Status : (no.ruter.avro.entity.actual.journey.status.Status) defaultValue(fields()[1]);
        record.EndStatus = fieldSetFlags()[2] ? this.EndStatus : (no.ruter.avro.entity.actual.journey.status.EndStatus) defaultValue(fields()[2]);
        record.LastActualCallRef = fieldSetFlags()[3] ? this.LastActualCallRef : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.NextActualCallRef = fieldSetFlags()[4] ? this.NextActualCallRef : (java.lang.CharSequence) defaultValue(fields()[4]);
        if (JourneyDelayBuilder != null) {
          record.JourneyDelay = this.JourneyDelayBuilder.build();
        } else {
          record.JourneyDelay = fieldSetFlags()[5] ? this.JourneyDelay : (no.ruter.avro.entity.actual.journey.status.JourneyDelay) defaultValue(fields()[5]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EntityPartition>
    WRITER$ = (org.apache.avro.io.DatumWriter<EntityPartition>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EntityPartition>
    READER$ = (org.apache.avro.io.DatumReader<EntityPartition>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
