/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.ruter.avro.entity.actual.journey.status;
@SuppressWarnings("all")
/** Source of delay information. */
@org.apache.avro.specific.AvroGenerated
public enum Source {
  SIS, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Source\",\"namespace\":\"no.ruter.avro.entity.actual.journey.status\",\"doc\":\"Source of delay information.\",\"symbols\":[\"SIS\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
