/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.ruter.avro.entity.actual.call.key;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** The data of the entity partition */
@org.apache.avro.specific.AvroGenerated
public class EntityPartition extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7941155032322288217L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EntityPartition\",\"namespace\":\"no.ruter.avro.entity.actual.call.key\",\"doc\":\"The data of the entity partition\",\"fields\":[{\"name\":\"Key\",\"type\":\"string\",\"doc\":\"The key of an entity. All entities must use the key attribute to store their primary key\"},{\"name\":\"VehicleRef\",\"type\":\"string\",\"doc\":\"Reference to the vehicle that made the call.\"},{\"name\":\"QuayRef\",\"type\":[\"null\",\"string\"],\"doc\":\"Reference to the quay the call is on if known.\",\"default\":null},{\"name\":\"ActualJourneyRef\",\"type\":[\"null\",\"string\"],\"doc\":\"Reference to actual journey this actual call is on if known.\",\"default\":null},{\"name\":\"ActualBlockRef\",\"type\":[\"null\",\"string\"],\"doc\":\"Reference to actual block this actual call is on if known.\",\"default\":null},{\"name\":\"PreviousActualCallRef\",\"type\":[\"null\",\"string\"],\"doc\":\"Reference to the previous actual call.\",\"default\":null},{\"name\":\"NextActualCallRef\",\"type\":[\"null\",\"string\"],\"doc\":\"Reference to the next actual call.\",\"default\":null},{\"name\":\"PositionInJourney\",\"type\":{\"type\":\"enum\",\"name\":\"PositionInJourney\",\"doc\":\"The call's position in the journey\",\"symbols\":[\"FIRST\",\"INTERMEDIATE\",\"LAST\"]},\"doc\":\"The call's position in the journey\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EntityPartition> ENCODER =
      new BinaryMessageEncoder<EntityPartition>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EntityPartition> DECODER =
      new BinaryMessageDecoder<EntityPartition>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EntityPartition> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EntityPartition> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EntityPartition>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EntityPartition to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EntityPartition from a ByteBuffer. */
  public static EntityPartition fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The key of an entity. All entities must use the key attribute to store their primary key */
  @Deprecated public java.lang.CharSequence Key;
  /** Reference to the vehicle that made the call. */
  @Deprecated public java.lang.CharSequence VehicleRef;
  /** Reference to the quay the call is on if known. */
  @Deprecated public java.lang.CharSequence QuayRef;
  /** Reference to actual journey this actual call is on if known. */
  @Deprecated public java.lang.CharSequence ActualJourneyRef;
  /** Reference to actual block this actual call is on if known. */
  @Deprecated public java.lang.CharSequence ActualBlockRef;
  /** Reference to the previous actual call. */
  @Deprecated public java.lang.CharSequence PreviousActualCallRef;
  /** Reference to the next actual call. */
  @Deprecated public java.lang.CharSequence NextActualCallRef;
  /** The call's position in the journey */
  @Deprecated public no.ruter.avro.entity.actual.call.key.PositionInJourney PositionInJourney;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EntityPartition() {}

  /**
   * All-args constructor.
   * @param Key The key of an entity. All entities must use the key attribute to store their primary key
   * @param VehicleRef Reference to the vehicle that made the call.
   * @param QuayRef Reference to the quay the call is on if known.
   * @param ActualJourneyRef Reference to actual journey this actual call is on if known.
   * @param ActualBlockRef Reference to actual block this actual call is on if known.
   * @param PreviousActualCallRef Reference to the previous actual call.
   * @param NextActualCallRef Reference to the next actual call.
   * @param PositionInJourney The call's position in the journey
   */
  public EntityPartition(java.lang.CharSequence Key, java.lang.CharSequence VehicleRef, java.lang.CharSequence QuayRef, java.lang.CharSequence ActualJourneyRef, java.lang.CharSequence ActualBlockRef, java.lang.CharSequence PreviousActualCallRef, java.lang.CharSequence NextActualCallRef, no.ruter.avro.entity.actual.call.key.PositionInJourney PositionInJourney) {
    this.Key = Key;
    this.VehicleRef = VehicleRef;
    this.QuayRef = QuayRef;
    this.ActualJourneyRef = ActualJourneyRef;
    this.ActualBlockRef = ActualBlockRef;
    this.PreviousActualCallRef = PreviousActualCallRef;
    this.NextActualCallRef = NextActualCallRef;
    this.PositionInJourney = PositionInJourney;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Key;
    case 1: return VehicleRef;
    case 2: return QuayRef;
    case 3: return ActualJourneyRef;
    case 4: return ActualBlockRef;
    case 5: return PreviousActualCallRef;
    case 6: return NextActualCallRef;
    case 7: return PositionInJourney;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Key = (java.lang.CharSequence)value$; break;
    case 1: VehicleRef = (java.lang.CharSequence)value$; break;
    case 2: QuayRef = (java.lang.CharSequence)value$; break;
    case 3: ActualJourneyRef = (java.lang.CharSequence)value$; break;
    case 4: ActualBlockRef = (java.lang.CharSequence)value$; break;
    case 5: PreviousActualCallRef = (java.lang.CharSequence)value$; break;
    case 6: NextActualCallRef = (java.lang.CharSequence)value$; break;
    case 7: PositionInJourney = (no.ruter.avro.entity.actual.call.key.PositionInJourney)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Key' field.
   * @return The key of an entity. All entities must use the key attribute to store their primary key
   */
  public java.lang.CharSequence getKey() {
    return Key;
  }

  /**
   * Sets the value of the 'Key' field.
   * The key of an entity. All entities must use the key attribute to store their primary key
   * @param value the value to set.
   */
  public void setKey(java.lang.CharSequence value) {
    this.Key = value;
  }

  /**
   * Gets the value of the 'VehicleRef' field.
   * @return Reference to the vehicle that made the call.
   */
  public java.lang.CharSequence getVehicleRef() {
    return VehicleRef;
  }

  /**
   * Sets the value of the 'VehicleRef' field.
   * Reference to the vehicle that made the call.
   * @param value the value to set.
   */
  public void setVehicleRef(java.lang.CharSequence value) {
    this.VehicleRef = value;
  }

  /**
   * Gets the value of the 'QuayRef' field.
   * @return Reference to the quay the call is on if known.
   */
  public java.lang.CharSequence getQuayRef() {
    return QuayRef;
  }

  /**
   * Sets the value of the 'QuayRef' field.
   * Reference to the quay the call is on if known.
   * @param value the value to set.
   */
  public void setQuayRef(java.lang.CharSequence value) {
    this.QuayRef = value;
  }

  /**
   * Gets the value of the 'ActualJourneyRef' field.
   * @return Reference to actual journey this actual call is on if known.
   */
  public java.lang.CharSequence getActualJourneyRef() {
    return ActualJourneyRef;
  }

  /**
   * Sets the value of the 'ActualJourneyRef' field.
   * Reference to actual journey this actual call is on if known.
   * @param value the value to set.
   */
  public void setActualJourneyRef(java.lang.CharSequence value) {
    this.ActualJourneyRef = value;
  }

  /**
   * Gets the value of the 'ActualBlockRef' field.
   * @return Reference to actual block this actual call is on if known.
   */
  public java.lang.CharSequence getActualBlockRef() {
    return ActualBlockRef;
  }

  /**
   * Sets the value of the 'ActualBlockRef' field.
   * Reference to actual block this actual call is on if known.
   * @param value the value to set.
   */
  public void setActualBlockRef(java.lang.CharSequence value) {
    this.ActualBlockRef = value;
  }

  /**
   * Gets the value of the 'PreviousActualCallRef' field.
   * @return Reference to the previous actual call.
   */
  public java.lang.CharSequence getPreviousActualCallRef() {
    return PreviousActualCallRef;
  }

  /**
   * Sets the value of the 'PreviousActualCallRef' field.
   * Reference to the previous actual call.
   * @param value the value to set.
   */
  public void setPreviousActualCallRef(java.lang.CharSequence value) {
    this.PreviousActualCallRef = value;
  }

  /**
   * Gets the value of the 'NextActualCallRef' field.
   * @return Reference to the next actual call.
   */
  public java.lang.CharSequence getNextActualCallRef() {
    return NextActualCallRef;
  }

  /**
   * Sets the value of the 'NextActualCallRef' field.
   * Reference to the next actual call.
   * @param value the value to set.
   */
  public void setNextActualCallRef(java.lang.CharSequence value) {
    this.NextActualCallRef = value;
  }

  /**
   * Gets the value of the 'PositionInJourney' field.
   * @return The call's position in the journey
   */
  public no.ruter.avro.entity.actual.call.key.PositionInJourney getPositionInJourney() {
    return PositionInJourney;
  }

  /**
   * Sets the value of the 'PositionInJourney' field.
   * The call's position in the journey
   * @param value the value to set.
   */
  public void setPositionInJourney(no.ruter.avro.entity.actual.call.key.PositionInJourney value) {
    this.PositionInJourney = value;
  }

  /**
   * Creates a new EntityPartition RecordBuilder.
   * @return A new EntityPartition RecordBuilder
   */
  public static no.ruter.avro.entity.actual.call.key.EntityPartition.Builder newBuilder() {
    return new no.ruter.avro.entity.actual.call.key.EntityPartition.Builder();
  }

  /**
   * Creates a new EntityPartition RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EntityPartition RecordBuilder
   */
  public static no.ruter.avro.entity.actual.call.key.EntityPartition.Builder newBuilder(no.ruter.avro.entity.actual.call.key.EntityPartition.Builder other) {
    return new no.ruter.avro.entity.actual.call.key.EntityPartition.Builder(other);
  }

  /**
   * Creates a new EntityPartition RecordBuilder by copying an existing EntityPartition instance.
   * @param other The existing instance to copy.
   * @return A new EntityPartition RecordBuilder
   */
  public static no.ruter.avro.entity.actual.call.key.EntityPartition.Builder newBuilder(no.ruter.avro.entity.actual.call.key.EntityPartition other) {
    return new no.ruter.avro.entity.actual.call.key.EntityPartition.Builder(other);
  }

  /**
   * RecordBuilder for EntityPartition instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EntityPartition>
    implements org.apache.avro.data.RecordBuilder<EntityPartition> {

    /** The key of an entity. All entities must use the key attribute to store their primary key */
    private java.lang.CharSequence Key;
    /** Reference to the vehicle that made the call. */
    private java.lang.CharSequence VehicleRef;
    /** Reference to the quay the call is on if known. */
    private java.lang.CharSequence QuayRef;
    /** Reference to actual journey this actual call is on if known. */
    private java.lang.CharSequence ActualJourneyRef;
    /** Reference to actual block this actual call is on if known. */
    private java.lang.CharSequence ActualBlockRef;
    /** Reference to the previous actual call. */
    private java.lang.CharSequence PreviousActualCallRef;
    /** Reference to the next actual call. */
    private java.lang.CharSequence NextActualCallRef;
    /** The call's position in the journey */
    private no.ruter.avro.entity.actual.call.key.PositionInJourney PositionInJourney;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.ruter.avro.entity.actual.call.key.EntityPartition.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Key)) {
        this.Key = data().deepCopy(fields()[0].schema(), other.Key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.VehicleRef)) {
        this.VehicleRef = data().deepCopy(fields()[1].schema(), other.VehicleRef);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.QuayRef)) {
        this.QuayRef = data().deepCopy(fields()[2].schema(), other.QuayRef);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ActualJourneyRef)) {
        this.ActualJourneyRef = data().deepCopy(fields()[3].schema(), other.ActualJourneyRef);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ActualBlockRef)) {
        this.ActualBlockRef = data().deepCopy(fields()[4].schema(), other.ActualBlockRef);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.PreviousActualCallRef)) {
        this.PreviousActualCallRef = data().deepCopy(fields()[5].schema(), other.PreviousActualCallRef);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.NextActualCallRef)) {
        this.NextActualCallRef = data().deepCopy(fields()[6].schema(), other.NextActualCallRef);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.PositionInJourney)) {
        this.PositionInJourney = data().deepCopy(fields()[7].schema(), other.PositionInJourney);
        fieldSetFlags()[7] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EntityPartition instance
     * @param other The existing instance to copy.
     */
    private Builder(no.ruter.avro.entity.actual.call.key.EntityPartition other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Key)) {
        this.Key = data().deepCopy(fields()[0].schema(), other.Key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.VehicleRef)) {
        this.VehicleRef = data().deepCopy(fields()[1].schema(), other.VehicleRef);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.QuayRef)) {
        this.QuayRef = data().deepCopy(fields()[2].schema(), other.QuayRef);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ActualJourneyRef)) {
        this.ActualJourneyRef = data().deepCopy(fields()[3].schema(), other.ActualJourneyRef);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ActualBlockRef)) {
        this.ActualBlockRef = data().deepCopy(fields()[4].schema(), other.ActualBlockRef);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.PreviousActualCallRef)) {
        this.PreviousActualCallRef = data().deepCopy(fields()[5].schema(), other.PreviousActualCallRef);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.NextActualCallRef)) {
        this.NextActualCallRef = data().deepCopy(fields()[6].schema(), other.NextActualCallRef);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.PositionInJourney)) {
        this.PositionInJourney = data().deepCopy(fields()[7].schema(), other.PositionInJourney);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'Key' field.
      * The key of an entity. All entities must use the key attribute to store their primary key
      * @return The value.
      */
    public java.lang.CharSequence getKey() {
      return Key;
    }

    /**
      * Sets the value of the 'Key' field.
      * The key of an entity. All entities must use the key attribute to store their primary key
      * @param value The value of 'Key'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder setKey(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Key' field has been set.
      * The key of an entity. All entities must use the key attribute to store their primary key
      * @return True if the 'Key' field has been set, false otherwise.
      */
    public boolean hasKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Key' field.
      * The key of an entity. All entities must use the key attribute to store their primary key
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder clearKey() {
      Key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'VehicleRef' field.
      * Reference to the vehicle that made the call.
      * @return The value.
      */
    public java.lang.CharSequence getVehicleRef() {
      return VehicleRef;
    }

    /**
      * Sets the value of the 'VehicleRef' field.
      * Reference to the vehicle that made the call.
      * @param value The value of 'VehicleRef'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder setVehicleRef(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.VehicleRef = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'VehicleRef' field has been set.
      * Reference to the vehicle that made the call.
      * @return True if the 'VehicleRef' field has been set, false otherwise.
      */
    public boolean hasVehicleRef() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'VehicleRef' field.
      * Reference to the vehicle that made the call.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder clearVehicleRef() {
      VehicleRef = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'QuayRef' field.
      * Reference to the quay the call is on if known.
      * @return The value.
      */
    public java.lang.CharSequence getQuayRef() {
      return QuayRef;
    }

    /**
      * Sets the value of the 'QuayRef' field.
      * Reference to the quay the call is on if known.
      * @param value The value of 'QuayRef'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder setQuayRef(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.QuayRef = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'QuayRef' field has been set.
      * Reference to the quay the call is on if known.
      * @return True if the 'QuayRef' field has been set, false otherwise.
      */
    public boolean hasQuayRef() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'QuayRef' field.
      * Reference to the quay the call is on if known.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder clearQuayRef() {
      QuayRef = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ActualJourneyRef' field.
      * Reference to actual journey this actual call is on if known.
      * @return The value.
      */
    public java.lang.CharSequence getActualJourneyRef() {
      return ActualJourneyRef;
    }

    /**
      * Sets the value of the 'ActualJourneyRef' field.
      * Reference to actual journey this actual call is on if known.
      * @param value The value of 'ActualJourneyRef'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder setActualJourneyRef(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ActualJourneyRef = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ActualJourneyRef' field has been set.
      * Reference to actual journey this actual call is on if known.
      * @return True if the 'ActualJourneyRef' field has been set, false otherwise.
      */
    public boolean hasActualJourneyRef() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ActualJourneyRef' field.
      * Reference to actual journey this actual call is on if known.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder clearActualJourneyRef() {
      ActualJourneyRef = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'ActualBlockRef' field.
      * Reference to actual block this actual call is on if known.
      * @return The value.
      */
    public java.lang.CharSequence getActualBlockRef() {
      return ActualBlockRef;
    }

    /**
      * Sets the value of the 'ActualBlockRef' field.
      * Reference to actual block this actual call is on if known.
      * @param value The value of 'ActualBlockRef'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder setActualBlockRef(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.ActualBlockRef = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'ActualBlockRef' field has been set.
      * Reference to actual block this actual call is on if known.
      * @return True if the 'ActualBlockRef' field has been set, false otherwise.
      */
    public boolean hasActualBlockRef() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'ActualBlockRef' field.
      * Reference to actual block this actual call is on if known.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder clearActualBlockRef() {
      ActualBlockRef = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'PreviousActualCallRef' field.
      * Reference to the previous actual call.
      * @return The value.
      */
    public java.lang.CharSequence getPreviousActualCallRef() {
      return PreviousActualCallRef;
    }

    /**
      * Sets the value of the 'PreviousActualCallRef' field.
      * Reference to the previous actual call.
      * @param value The value of 'PreviousActualCallRef'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder setPreviousActualCallRef(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.PreviousActualCallRef = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'PreviousActualCallRef' field has been set.
      * Reference to the previous actual call.
      * @return True if the 'PreviousActualCallRef' field has been set, false otherwise.
      */
    public boolean hasPreviousActualCallRef() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'PreviousActualCallRef' field.
      * Reference to the previous actual call.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder clearPreviousActualCallRef() {
      PreviousActualCallRef = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'NextActualCallRef' field.
      * Reference to the next actual call.
      * @return The value.
      */
    public java.lang.CharSequence getNextActualCallRef() {
      return NextActualCallRef;
    }

    /**
      * Sets the value of the 'NextActualCallRef' field.
      * Reference to the next actual call.
      * @param value The value of 'NextActualCallRef'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder setNextActualCallRef(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.NextActualCallRef = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'NextActualCallRef' field has been set.
      * Reference to the next actual call.
      * @return True if the 'NextActualCallRef' field has been set, false otherwise.
      */
    public boolean hasNextActualCallRef() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'NextActualCallRef' field.
      * Reference to the next actual call.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder clearNextActualCallRef() {
      NextActualCallRef = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'PositionInJourney' field.
      * The call's position in the journey
      * @return The value.
      */
    public no.ruter.avro.entity.actual.call.key.PositionInJourney getPositionInJourney() {
      return PositionInJourney;
    }

    /**
      * Sets the value of the 'PositionInJourney' field.
      * The call's position in the journey
      * @param value The value of 'PositionInJourney'.
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder setPositionInJourney(no.ruter.avro.entity.actual.call.key.PositionInJourney value) {
      validate(fields()[7], value);
      this.PositionInJourney = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'PositionInJourney' field has been set.
      * The call's position in the journey
      * @return True if the 'PositionInJourney' field has been set, false otherwise.
      */
    public boolean hasPositionInJourney() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'PositionInJourney' field.
      * The call's position in the journey
      * @return This builder.
      */
    public no.ruter.avro.entity.actual.call.key.EntityPartition.Builder clearPositionInJourney() {
      PositionInJourney = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EntityPartition build() {
      try {
        EntityPartition record = new EntityPartition();
        record.Key = fieldSetFlags()[0] ? this.Key : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.VehicleRef = fieldSetFlags()[1] ? this.VehicleRef : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.QuayRef = fieldSetFlags()[2] ? this.QuayRef : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ActualJourneyRef = fieldSetFlags()[3] ? this.ActualJourneyRef : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.ActualBlockRef = fieldSetFlags()[4] ? this.ActualBlockRef : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.PreviousActualCallRef = fieldSetFlags()[5] ? this.PreviousActualCallRef : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.NextActualCallRef = fieldSetFlags()[6] ? this.NextActualCallRef : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.PositionInJourney = fieldSetFlags()[7] ? this.PositionInJourney : (no.ruter.avro.entity.actual.call.key.PositionInJourney) defaultValue(fields()[7]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EntityPartition>
    WRITER$ = (org.apache.avro.io.DatumWriter<EntityPartition>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EntityPartition>
    READER$ = (org.apache.avro.io.DatumReader<EntityPartition>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
