/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.ruter.avro.entity.actual.call.key;
@SuppressWarnings("all")
/** The call's position in the journey */
@org.apache.avro.specific.AvroGenerated
public enum PositionInJourney {
  FIRST, INTERMEDIATE, LAST  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PositionInJourney\",\"namespace\":\"no.ruter.avro.entity.actual.call.key\",\"doc\":\"The call's position in the journey\",\"symbols\":[\"FIRST\",\"INTERMEDIATE\",\"LAST\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
