/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.ruter.avro.entity.actual.call.status;
@SuppressWarnings("all")
/** Last known status of the call. */
@org.apache.avro.specific.AvroGenerated
public enum Status {
  COMMITTED, ARRIVED, DONE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"no.ruter.avro.entity.actual.call.status\",\"doc\":\"Last known status of the call.\",\"symbols\":[\"COMMITTED\",\"ARRIVED\",\"DONE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
